name: Tag AWS Accounts 

on:
  workflow_dispatch:
    inputs:
      tagEnvironment:
        type: choice
        description: Select the Environment Tag
        options: 
        - "Key=environment,Value=nonprod"
        - "Key=environment,Value=prod"
      Resource_id:
        required: true
    

jobs:
  AccountTagging:
    runs-on: ubuntu-latest

    steps:
    - name: Execute Tagging cli
      run: echo "aws organizations tag-resource --resource-id ${{ github.event.inputs.Resource_id }} --tags ${{ github.event.inputs.tagEnvironment }}"
