name: Tag AWS Accounts 

on:
  workflow_dispatch:
    inputs:
      tagEnvironment:
        type: choice
        description: Select the Environment Tag
        options: 
        - "Key=environment,Value=nonprod"
        - "Key=environment,Value=prod"
      Resource_id:
        required: true
env: 
  AWS_REGION : us-east-1 #Change to reflect your Region


jobs:
  AccountTagging:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::199909611641:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHubAction-AssumeRoleWithAction
          aws-region: ${{ env.AWS_REGION }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Execute Tagging cli
        run: echo "aws organizations tag-resource --resource-id ${{ github.event.inputs.Resource_id }} --tags ${{ github.event.inputs.tagEnvironment }}"
